import React, { useEffect, useRef, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import { api } from '../utils/api';
import Navbar from '../components/Navbar';
import Logo from '../components/Logo';

/* ── SVG Icons ──────────────────────────────────────────────────── */
const icons = {
  brain: (
    <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">
      <path d="M9.5 2A2.5 2.5 0 0 1 12 4.5v15a2.5 2.5 0 0 1-4.96-.44 2.5 2.5 0 0 1-2.96-3.08 3 3 0 0 1-.34-5.58 2.5 2.5 0 0 1 1.32-4.24 2.5 2.5 0 0 1 1.98-3A2.5 2.5 0 0 1 9.5 2Z"/>
      <path d="M14.5 2A2.5 2.5 0 0 0 12 4.5v15a2.5 2.5 0 0 0 4.96-.44 2.5 2.5 0 0 0 2.96-3.08 3 3 0 0 0 .34-5.58 2.5 2.5 0 0 0-1.32-4.24 2.5 2.5 0 0 0-1.98-3A2.5 2.5 0 0 0 14.5 2Z"/>
    </svg>
  ),
  chart: (
    <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">
      <line x1="18" y1="20" x2="18" y2="10"/><line x1="12" y1="20" x2="12" y2="4"/>
      <line x1="6" y1="20" x2="6" y2="14"/><line x1="2" y1="20" x2="22" y2="20"/>
    </svg>
  ),
  pulse: (
    <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">
      <path d="M22 12h-4l-3 9L9 3l-3 9H2"/>
    </svg>
  ),
  shield: (
    <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">
      <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/>
    </svg>
  ),
  clock: (
    <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">
      <circle cx="12" cy="12" r="10"/><polyline points="12 6 12 12 16 14"/>
    </svg>
  ),
  file: (
    <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">
      <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/>
      <polyline points="14 2 14 8 20 8"/>
      <line x1="16" y1="13" x2="8" y2="13"/><line x1="16" y1="17" x2="8" y2="17"/>
      <polyline points="10 9 9 9 8 9"/>
    </svg>
  ),
  arrowRight: (
    <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
      <line x1="5" y1="12" x2="19" y2="12"/><polyline points="12 5 19 12 12 19"/>
    </svg>
  ),
  zap: (
    <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">
      <polygon points="13 2 3 14 12 14 11 22 21 10 12 10 13 2"/>
    </svg>
  ),
};

/* ── Specialty definitions (SVG icons, no emojis) ───────────────── */
const SPECIALTIES = [
  { name: 'Cardiology',        icon: icons.pulse,  desc: 'ECGs, ACS, Heart Failure' },
  { name: 'Neurology',         icon: icons.brain,  desc: 'Stroke, Seizures, Headache' },
  { name: 'Emergency Medicine',icon: icons.zap,    desc: 'Trauma, Sepsis, ACLS' },
  { name: 'General Medicine',  icon: icons.shield, desc: 'Common presentations' },
  { name: 'Respiratory',       icon: icons.pulse,  desc: 'COPD, Asthma, PE' },
  { name: 'Pediatrics',        icon: icons.shield, desc: 'Neonatal, Growth, Fever' },
  { name: 'Psychiatry',        icon: icons.brain,  desc: 'MDD, Anxiety, Psychosis' },
  { name: 'Gastroenterology',  icon: icons.file,   desc: 'GI Bleed, IBD, Liver' },
  { name: 'Endocrinology',     icon: icons.chart,  desc: 'Diabetes, Thyroid, DKA' },
  { name: 'Oncology',          icon: icons.shield, desc: 'Staging, Paraneoplastic' },
];

const FEATURES = [
  {
    icon: icons.pulse,
    title: 'AI Patients That Feel Real',
    desc: 'Every patient is generated by LLMs with a unique history, personality, and symptom presentation. No two sessions are identical.',
  },
  {
    icon: icons.shield,
    title: 'Zero-Risk Environment',
    desc: 'Make clinical mistakes, miss diagnoses, and learn from feedback. No real patients, no consequences — only growth.',
  },
  {
    icon: icons.chart,
    title: 'Rubric-Based Evaluation',
    desc: 'After each session, get scored across history-taking, differential reasoning, red flag detection, and clinical communication.',
  },
  {
    icon: icons.clock,
    title: 'Emergency Timed Scenarios',
    desc: 'Activate emergency mode for high-pressure, time-limited cases that simulate real on-call decision-making.',
  },
  {
    icon: icons.file,
    title: 'Integrated Medical Reports',
    desc: 'Access ECGs, lab panels, and imaging directly in the simulator. Learn to interpret reports in clinical context.',
  },
  {
    icon: icons.brain,
    title: 'Multi-Specialty Case Bank',
    desc: 'Train across cardiology, neurology, emergency medicine, pediatrics, and 10+ other specialties.',
  },
];

/* ── ECG SVG path (one full heartbeat cycle repeated) ───────────── */
const ECG_PATH = `M0,30 L60,30 L70,30 L80,5 L90,55 L100,30 L115,30 L120,30 L130,30 L140,30 L150,30 
  L210,30 L220,30 L230,5 L240,55 L250,30 L265,30 L270,30 L280,30 L290,30 L300,30 
  L360,30 L370,30 L380,5 L390,55 L400,30 L415,30 L420,30 L430,30 L440,30 L450,30
  L510,30 L520,30 L530,5 L540,55 L550,30 L565,30 L570,30 L580,30 L590,30 L600,30`;

/* ── Live chat preview messages ─────────────────────────────────── */
const DEMO_MSGS = [
  { role: 'patient', text: "Hello doctor. I'm Marcus Webb. I've had crushing chest pain for the past 2 hours. It started suddenly at rest." },
  { role: 'doctor',  text: "Is the pain radiating anywhere — your jaw, left arm, or back?" },
  { role: 'patient', text: "Yes... my left arm and jaw. I'm also feeling quite short of breath and sweaty." },
  { role: 'doctor',  text: "Any previous cardiac history? Are you on any medications?" },
  { role: 'patient', text: "I had high blood pressure for 10 years. I take lisinopril, but I haven't taken it in a few days." },
  { role: 'doctor',  text: "How severe is the pain on a scale of 1 to 10?" },
  { role: 'patient', text: "Nine. Maybe a ten. It's the worst pain I've ever felt in my life." },
];

/* ── Animated stat counter ──────────────────────────────────────── */
function AnimatedCount({ to, suffix = '' }) {
  const [val, setVal] = useState(0);
  const ref = useRef(null);
  const started = useRef(false);

  useEffect(() => {
    const obs = new IntersectionObserver(([entry]) => {
      if (entry.isIntersecting && !started.current) {
        started.current = true;
        const duration = 1400;
        const start = performance.now();
        const tick = (now) => {
          const elapsed = now - start;
          const progress = Math.min(elapsed / duration, 1);
          const eased = 1 - Math.pow(1 - progress, 3);
          setVal(Math.round(eased * to));
          if (progress < 1) requestAnimationFrame(tick);
        };
        requestAnimationFrame(tick);
      }
    }, { threshold: 0.5 });
    if (ref.current) obs.observe(ref.current);
    return () => obs.disconnect();
  }, [to]);

  return <span ref={ref}>{val}{suffix}</span>;
}

/* ── Main component ─────────────────────────────────────────────── */
export default function Landing() {
  const { user } = useAuth();
  const navigate = useNavigate();

  // Live demo chat animation
  const [visibleMsgs, setVisibleMsgs] = useState(1);
  const previewRef = useRef(null);
  useEffect(() => {
    if (visibleMsgs >= DEMO_MSGS.length) return;
    const t = setTimeout(() => setVisibleMsgs(n => n + 1), 2200);
    return () => clearTimeout(t);
  }, [visibleMsgs]);
  // Auto-scroll chat preview
  useEffect(() => {
    if (previewRef.current) {
      previewRef.current.scrollTop = previewRef.current.scrollHeight;
    }
  }, [visibleMsgs]);

  // Fetch live stats from API health endpoint
  const [liveStats, setLiveStats] = useState(null);
  useEffect(() => {
    api('/health').then(d => setLiveStats(d)).catch(() => {});
  }, []);

  const handleStart = () => navigate(user ? '/simulator' : '/register');
  const handleDemo  = () => navigate('/simulator?demo=cardiology');

  return (
    <div style={{ background: 'var(--bg)', minHeight: '100vh' }}>
      <Navbar />

      {/* ── HERO ─────────────────────────────────────────────────── */}
      <section className="landing-hero" id="hero">
        <div className="hero-grid-bg" aria-hidden="true" />
        <div className="hero-glow" aria-hidden="true" />

        <div className="container" style={{ position: 'relative', zIndex: 1 }}>
          <div style={{
            display: 'grid',
            gridTemplateColumns: '1fr 1fr',
            gap: 64,
            alignItems: 'center',
          }}>
            {/* Left: Copy */}
            <div>
              <div className="hero-eyebrow">
                Clinical Training Platform
              </div>

              <h1 className="hero-title">
                <span>The simulator</span>
                <span>medical students</span>
                <span>
                  actually{' '}
                  <span style={{
                    background: 'var(--grad-brand)',
                    WebkitBackgroundClip: 'text',
                    WebkitTextFillColor: 'transparent',
                    backgroundClip: 'text',
                  }}>
                    use.
                  </span>
                </span>
              </h1>

              <p className="hero-sub">
                Practice patient interviews, order investigations, and diagnose complex cases —
                with AI patients that respond like real people.
                Instant rubric-based feedback after every session.
              </p>

              <div className="hero-actions">
                <button onClick={handleStart} className="btn btn-primary btn-xl">
                  Start Practicing
                  <span style={{ display: 'flex', alignItems: 'center' }}>{icons.arrowRight}</span>
                </button>
                <button onClick={handleDemo} className="btn btn-outline btn-xl">
                  Try Demo — Cardiology
                </button>
              </div>

              {/* Inline trust signals — no emojis, just data */}
              <div style={{ display: 'flex', gap: 24, marginTop: 36, flexWrap: 'wrap' }}>
                {[
                  { val: '10+', label: 'Specialties' },
                  { val: '50+', label: 'Case scenarios' },
                  { val: 'AI', label: 'Powered feedback' },
                ].map(({ val, label }) => (
                  <div key={label}>
                    <div style={{ fontSize: 'var(--fs-xl)', fontWeight: 800, color: 'var(--text)', fontFamily: 'var(--mono)' }}>{val}</div>
                    <div style={{ fontSize: 'var(--fs-xs)', color: 'var(--text-muted)', marginTop: 2 }}>{label}</div>
                  </div>
                ))}
              </div>
            </div>

            {/* Right: Live simulation preview */}
            <div style={{ position: 'relative' }}>
              {/* Glow behind preview */}
              <div style={{
                position: 'absolute', inset: -24,
                background: 'radial-gradient(ellipse at center, rgba(0,201,177,0.08) 0%, transparent 70%)',
                pointerEvents: 'none',
              }} aria-hidden="true" />

              <div className="hero-preview">
                {/* Window chrome */}
                <div className="preview-header">
                  <div className="preview-dots">
                    <div className="preview-dot" />
                    <div className="preview-dot" />
                    <div className="preview-dot" />
                  </div>
                  <div className="preview-label">CURA.AI — Simulation Lab</div>
                  <div style={{ display: 'flex', gap: 8, alignItems: 'center' }}>
                    <div style={{ width: 8, height: 8, borderRadius: '50%', background: 'var(--success)', boxShadow: '0 0 6px var(--success)' }} />
                    <span style={{ fontSize: 11, color: 'var(--text-muted)', fontFamily: 'var(--mono)' }}>AI Connected</span>
                  </div>
                </div>

                {/* Patient info bar */}
                <div style={{
                  padding: '10px 16px',
                  background: 'var(--surface-2)',
                  borderBottom: '1px solid var(--border)',
                  display: 'flex', alignItems: 'center', justifyContent: 'space-between',
                }}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
                    <div style={{
                      width: 32, height: 32, borderRadius: 8,
                      background: 'var(--teal-dim)',
                      border: '1px solid rgba(0,201,177,0.25)',
                      display: 'flex', alignItems: 'center', justifyContent: 'center',
                      fontSize: 13, fontWeight: 700, color: 'var(--teal)',
                    }}>MW</div>
                    <div>
                      <div style={{ fontSize: 13, fontWeight: 700, color: 'var(--text)' }}>Marcus Webb, 58M</div>
                      <div style={{ fontSize: 11, color: 'var(--text-muted)' }}>Cardiology · High urgency</div>
                    </div>
                  </div>
                  <div style={{
                    padding: '3px 10px', borderRadius: 999,
                    background: 'var(--danger-dim)', border: '1px solid rgba(248,113,113,0.2)',
                    fontSize: 11, fontWeight: 700, color: 'var(--danger)', fontFamily: 'var(--mono)',
                  }}>CRITICAL</div>
                </div>

                {/* Chat messages */}
                <div ref={previewRef} className="preview-chat" style={{ overflow: 'hidden', minHeight: 260 }}>
                  {DEMO_MSGS.slice(0, visibleMsgs).map((msg, i) => (
                    <div
                      key={i}
                      className={`preview-msg preview-msg-${msg.role}`}
                      style={{ animation: 'slideUp 200ms var(--ease)', opacity: 1 }}
                    >
                      {msg.text}
                    </div>
                  ))}
                  {visibleMsgs < DEMO_MSGS.length && (
                    <div className="typing-indicator" style={{ alignSelf: 'flex-start' }}>
                      <div className="typing-dot" /><div className="typing-dot" /><div className="typing-dot" />
                    </div>
                  )}
                </div>

                {/* Vitals footer */}
                <div className="preview-vitals">
                  {[
                    { val: '118', lbl: 'HR bpm' },
                    { val: '88/60', lbl: 'BP mmHg' },
                    { val: '92%', lbl: 'SpO₂' },
                    { val: '38.4°', lbl: 'Temp' },
                  ].map(({ val, lbl }) => (
                    <div key={lbl} className="preview-vital">
                      <div className="preview-vital-val">{val}</div>
                      <div className="preview-vital-lbl">{lbl}</div>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* ECG line at bottom */}
        <div className="ecg-container" aria-hidden="true">
          <svg className="ecg-line" viewBox="0 0 600 60" preserveAspectRatio="none" fill="none">
            <path d={ECG_PATH} stroke="var(--teal)" strokeWidth="1.5" vectorEffect="non-scaling-stroke" />
          </svg>
        </div>
      </section>

      {/* ── STATS BAR ────────────────────────────────────────────── */}
      <section className="stats-bar">
        <div className="container">
          <div className="stats-bar-inner">
            {[
              { num: 50, suffix: '+', label: 'Clinical cases' },
              { num: 10, suffix: '+', label: 'Medical specialties' },
              { num: 3,  suffix: '',  label: 'AI providers supported' },
              { num: liveStats?.totalSessions || 200, suffix: '+', label: 'Sessions completed' },
            ].map(({ num, suffix, label }) => (
              <div key={label} className="stat-item">
                <div className="stat-item-num">
                  <AnimatedCount to={num} /><span>{suffix}</span>
                </div>
                <div className="stat-item-lbl">{label}</div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── SPECIALTIES ──────────────────────────────────────────── */}
      <section className="section-sm" style={{ borderBottom: '1px solid var(--border)' }}>
        <div className="container">
          <div className="section-label">Case Library</div>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-end', marginBottom: 32, flexWrap: 'wrap', gap: 16 }}>
            <h2 className="section-title" style={{ margin: 0 }}>
              Train across every specialty
            </h2>
            <p style={{ fontSize: 'var(--fs-sm)', color: 'var(--text-muted)', maxWidth: 360 }}>
              AI generates unique cases on demand for any specialty you choose.
              No case is repeated.
            </p>
          </div>

          <div className="specialties-scroll-container">
            <div className="specialties-scroll-track" role="list">
              <div className="specialties-scroll-group">
                {SPECIALTIES.map(({ name, icon, desc }) => (
                  <button
                    key={name}
                    role="listitem"
                    className="specialty-chip"
                    onClick={() => navigate(`/simulator?demo=${encodeURIComponent(name.toLowerCase())}`)}
                    title={`Try a ${name} case`}
                  >
                    <div className="specialty-chip-icon">{icon}</div>
                    <div>
                      <div className="specialty-chip-name">{name}</div>
                      <div className="specialty-chip-count">{desc}</div>
                    </div>
                  </button>
                ))}
              </div>
              <div className="specialties-scroll-group" aria-hidden="true">
                {SPECIALTIES.map(({ name, icon, desc }) => (
                  <button
                    key={`${name}-dup`}
                    tabIndex="-1"
                    className="specialty-chip"
                    onClick={() => navigate(`/simulator?demo=${encodeURIComponent(name.toLowerCase())}`)}
                    title={`Try a ${name} case`}
                  >
                    <div className="specialty-chip-icon">{icon}</div>
                    <div>
                      <div className="specialty-chip-name">{name}</div>
                      <div className="specialty-chip-count">{desc}</div>
                    </div>
                  </button>
                ))}
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* ── FEATURES ─────────────────────────────────────────────── */}
      <section className="section" id="features">
        <div className="container">
          <div style={{ maxWidth: 600, marginBottom: 0 }}>
            <div className="section-label">Why CURA.AI</div>
            <h2 className="section-title">Built for how doctors actually learn</h2>
            <p className="section-sub">
              Not another video lecture or MCQ bank.
              CURA.AI puts you in the room with a patient and makes you think.
            </p>
          </div>

          <div className="feature-grid">
            {FEATURES.map(({ icon, title, desc }) => (
              <div key={title} className="feature-card">
                <div className="feature-icon">{icon}</div>
                <h3 className="feature-title">{title}</h3>
                <p className="feature-desc">{desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── HOW IT WORKS ─────────────────────────────────────────── */}
      <section className="section-sm" style={{ background: 'var(--surface)', borderTop: '1px solid var(--border)', borderBottom: '1px solid var(--border)' }}>
        <div className="container">
          <div className="section-label" style={{ textAlign: 'center' }}>Process</div>
          <h2 className="section-title" style={{ textAlign: 'center', marginBottom: 'var(--sp-3)' }}>
            From selection to feedback in minutes
          </h2>
          <p className="section-sub" style={{ textAlign: 'center', margin: '0 auto var(--sp-12)' }}>
            Three steps between you and your next clinical insight.
          </p>

          <div className="steps-grid">
            {[
              {
                num: '01',
                title: 'Choose a Case',
                desc: 'Pick a specialty or let CURA.AI generate a randomised scenario. Every case has unique vitals, history, and personality.',
              },
              {
                num: '02',
                title: 'Interview the Patient',
                desc: 'Ask questions in natural language. The AI patient responds authentically — including evasions, anxiety, and confusion.',
              },
              {
                num: '03',
                title: 'Diagnose & Review',
                desc: 'Submit your provisional diagnosis and reasoning. Receive rubric-based feedback covering what you got right, wrong, and missed.',
              },
            ].map(({ num, title, desc }) => (
              <div key={num} className="step-item">
                <div className="step-num">{num}</div>
                <h3 className="step-title">{title}</h3>
                <p className="step-desc">{desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── CTA ──────────────────────────────────────────────────── */}
      <section className="cta-section">
        <div className="container" style={{ position: 'relative', zIndex: 1 }}>
          <div
            className="hero-eyebrow"
            style={{ justifyContent: 'center', display: 'inline-flex', margin: '0 auto 24px' }}
          >
            Ready to practice?
          </div>
          <h2 className="cta-title">
            Your next patient<br />
            <span style={{ background: 'var(--grad-brand)', WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent', backgroundClip: 'text' }}>
              is waiting.
            </span>
          </h2>
          <p className="cta-sub">
            No credit card. No sign-up required for the demo.
            Full access with a free account.
          </p>
          <div style={{ display: 'flex', gap: 16, justifyContent: 'center', flexWrap: 'wrap' }}>
            <button onClick={handleStart} className="btn btn-primary btn-xl">
              {user ? 'Open Simulation Lab' : 'Create Free Account'}
              <span style={{ display: 'flex', alignItems: 'center' }}>{icons.arrowRight}</span>
            </button>
            <button onClick={handleDemo} className="btn btn-outline btn-xl">
              Try Demo — No Sign-up
            </button>
          </div>
        </div>
      </section>

      {/* ── FOOTER ───────────────────────────────────────────────── */}
      <footer className="footer" role="contentinfo">
        <div className="container">
          <div className="footer-grid">
            <div>
              <Logo size={28} />
              <p className="footer-brand-desc">
                The clinical training platform for medical students and early-career doctors.
                Practice diagnosis with realistic AI patients across every major specialty.
              </p>
            </div>
            <div>
              <div className="footer-col-title">Product</div>
              <div className="footer-links">
                <Link to="/features" className="footer-link">Features</Link>
                <Link to="/simulator" className="footer-link">Simulation Lab</Link>
                <Link to="/register" className="footer-link">Get Started</Link>
              </div>
            </div>
            <div>
              <div className="footer-col-title">Specialties</div>
              <div className="footer-links">
                {SPECIALTIES.slice(0, 4).map(s => (
                  <button
                    key={s.name}
                    className="footer-link"
                    style={{ background: 'none', border: 'none', textAlign: 'left', padding: 0, cursor: 'pointer' }}
                    onClick={() => navigate(`/simulator?demo=${encodeURIComponent(s.name.toLowerCase())}`)}
                  >
                    {s.name}
                  </button>
                ))}
              </div>
            </div>
            <div>
              <div className="footer-col-title">Company</div>
              <div className="footer-links">
                <Link to="/about" className="footer-link">About</Link>
              </div>
            </div>
          </div>

          <div className="footer-bottom">
            <span>© {new Date().getFullYear()} CURA.AI — Synapse Team</span>
            <span style={{ fontFamily: 'var(--mono)' }}>
              {liveStats ? (
                <span style={{ color: 'var(--success)' }}>● System Online</span>
              ) : (
                <span style={{ color: 'var(--text-faint)' }}>— Checking status...</span>
              )}
            </span>
          </div>
        </div>
      </footer>
    </div>
  );
}
